### ISSUE TITLE
About training speed

### ISSUE THREAD

**Issue by sunbinbin1991** [KeyKy/mobilenet-mxnet#10]
I use mxnet-mobilenet for train, but for my GPU 1080Ti, the input is 224*224,my training speed is about 50 sample/second,so is something wrong for my training, I can't find the reason, looking forward your reply

**Comment by sunbinbin1991** [comment]
After build a new version of mxnet, problem solved

**Comment by 408550969** [comment]
Hi, what's your speed after solved the problem?

**Comment by sunbinbin1991** [comment]
It depends  batchsize you choose, in my test my batchsize is about 128,and training samples about 955 sample/s, may this could helps

**Comment by 408550969** [comment]
Thanks! Excuse me,what's your GPU?

**Comment by sunbinbin1991** [comment]
GPU 1080TI

**Comment by 408550969** [comment]
Thanks!
