### ISSUE TITLE
Is this a MXNet version implementation of mobilenet?

### ISSUE THREAD

**Issue by ysh329** [KeyKy/mobilenet-mxnet#3]
I'm a little confused about `README.md`.

You wrote: `This model is converted from MobileNet-Caffe`. However, I found the operator your implemented `channelwise_convolution.cc`,`channelwise_convolution.cu` in [mxnet@c492b5b](https://github.com/KeyKy/mxnet/tree/c492b5b9adb745908a6f627fd5d078e78110f6e5).
Besides, does this `channelwise` equal to `depth-wise` convolution in original paper?

**Comment by KeyKy** [comment]
@ysh329 Sorry. i just copy the README.md from caffe. I only give a pretrained model. I am also waiting for high speed depth-wise convolution

**Comment by ysh329** [comment]
@KeyKy Thanks!

**Comment by ysh329** [comment]
@KeyKy My big brother, do u have email or wechat. I'm to implement a high perforance depth-wise convolution :laughing:

**Comment by KeyKy** [comment]
@ysh329 370846270@qq.com
wechat: xiaozhenyouni
 Nice!
