### ISSUE TITLE
why do you not push your code to MXNet?

### ISSUE THREAD

**Issue by qingzhouzhen** [KeyKy/mobilenet-mxnet#4]
I am interested in this implement of the article, but I wonder why you not push you code to 
https://github.com/dmlc/mxnet?
and can this modle work? I tried, but failed, I can not compile the whole prject now.

**Comment by KeyKy** [comment]
you can turn all channelwiseconvolution into conv with group and use the official mxnet.

**Comment by qingzhouzhen** [comment]
ok, Can this implementation work? hava you tested?

**Comment by KeyKy** [comment]
yes. it works

**Comment by qingzhouzhen** [comment]
OK, THX
