### ISSUE TITLE
execute failed

### ISSUE THREAD

**Issue by qingzhouzhen** [KeyKy/mobilenet-mxnet#6]
hello, I execute the score.py as below:
1 clone the whole project of yours mobilenet-mxnet
2 cd into mxnet
3 then I execute make command: make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1
4 lastly I execute python score.py --prefix=mobilenet --epoch=0 --data-val=/data/ILSVRC2012_img_test.rec 

In this step it went wrong:
(mobilenet) [hanqing@localhost mobilenet-mxnet]$ python score.py --prefix=mobilenet --epoch=0 --data-val=/data/ILSVRC2012_img_test.rec
[21:56:23] src/io/iter_image_recordio_2.cc:135: ImageRecordIOParser2: /data/ILSVRC2012_img_test.rec, use 4 threads for decoding..
[21:56:24] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.9.5. Attempting to upgrade...
[21:56:24] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
[21:56:25] src/operator/././cudnn_algoreg-inl.h:65: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[22:01:59] include/dmlc/././logging.h:304: [22:01:59] src/recordio.cc:125: Check failed: pbegin_ <= pend_ Invalid RecordIO Format

Stack trace returned 5 entries:
[bt] (0) /home/hanqing/anaconda2/envs/mobilenet/lib/python2.7/site-packages/mxnet-0.10.1-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc19RecordIOChunkReader10NextRecordEPNS_10InputSplit4BlobE+0xd86) [0x7f3747c89406]
[bt] (1) /home/hanqing/anaconda2/envs/mobilenet/lib/python2.7/site-packages/mxnet-0.10.1-py2.7.egg/mxnet/libmxnet.so(+0x10366ed) [0x7f37478986ed]
[bt] (2) /lib64/libgomp.so.1(+0x16435) [0x7f372e6e9435]
[bt] (3) /lib64/libpthread.so.0(+0x7dc5) [0x7f375a691dc5]
[bt] (4) /lib64/libc.so.6(clone+0x6d) [0x7f3759cb776d]

terminate called after throwing an instance of 'dmlc::Error'
  what():  [22:01:59] src/recordio.cc:125: Check failed: pbegin_ <= pend_ Invalid RecordIO Format

Stack trace returned 5 entries:
[bt] (0) /home/hanqing/anaconda2/envs/mobilenet/lib/python2.7/site-packages/mxnet-0.10.1-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc19RecordIOChunkReader10NextRecordEPNS_10InputSplit4BlobE+0xd86) [0x7f3747c89406]
[bt] (1) /home/hanqing/anaconda2/envs/mobilenet/lib/python2.7/site-packages/mxnet-0.10.1-py2.7.egg/mxnet/libmxnet.so(+0x10366ed) [0x7f37478986ed]
[bt] (2) /lib64/libgomp.so.1(+0x16435) [0x7f372e6e9435]
[bt] (3) /lib64/libpthread.so.0(+0x7dc5) [0x7f375a691dc5]
[bt] (4) /lib64/libc.so.6(clone+0x6d) [0x7f3759cb776d]

Aborted (core dumped)

Is there anything I do wrong?

**Comment by KeyKy** [comment]
It seems the problem of your .rec file.

**Comment by qingzhouzhen** [comment]
yes, it is my .rec`problem
