### ISSUE TITLE
 Operator ChannelwiseConvolution is not registered

### ISSUE THREAD

**Issue by sunbinbin1991** [KeyKy/mobilenet-mxnet#7]
Dear writer, ths for your works,
I have a bug when use your model to get a my own fine-tune  model,

> mxnet.base.MXNetError: Failed loading Op conv2_1_dw of type ChannelwiseConvolution: [19:46:46] D:\Program Files (x86)\Jenkins\workspace\mxnet\mxnet\nnvm\src\core\op.cc:55: Check failed: op != nullptr Operator ChannelwiseConvolution is not registered

So, what's the reason for this, ChannelwiseConvolution is not found?

**Comment by KeyKy** [comment]
you can check the ChannelwiseConvolution operator in my mxnet and i add a submodule.
