### ISSUE TITLE
 fast Depthwise mxnet operator

### ISSUE THREAD

**Issue by vsooda** [KeyKy/mobilenet-mxnet#8]
@KeyKy Would you mind update the fast depthwise operator. or could you describe the key for implement fast operator. Thank you.

**Comment by KeyKy** [comment]
@vsooda fast depthwise operator is implemented by just copy the cuda code from ^-^ [url](https://github.com/BVLC/caffe/pull/5665). And then you can get the 2ms/image.

**Comment by ccJia** [comment]
@KeyKy Have some good idea or implement on CPU T-T  ??

**Comment by KeyKy** [comment]
@ccJia fast depthwise operator (which num_group == num_outputs) should be calculated in multi-threaded channel-by-channel. According to tencent's ncnn, I think sliding window (highly optimized, which also using in https://github.com/BVLC/caffe/pull/5665) maybe faster than im2col+GEMM.

**Comment by ccJia** [comment]
@KeyKy  OK, thank you . Let me have a try ^-^.

**Comment by KeyKy** [comment]
@ccJia looking forward to your job. Could you share with me after you have done the work? ^-^

**Comment by ccJia** [comment]
@KeyKy Some of my friends told me that the direct convolution like NCNN is not work.....

**Comment by KeyKy** [comment]
@ccJia Did they explain the reason or they try?

**Comment by ccJia** [comment]
@KeyKy They tried on Win.

**Comment by KeyKy** [comment]
@ccJia OK. I will try it in my spare time.

**Comment by ccJia** [comment]
@KeyKy waiting your good news .

**Comment by vsooda** [comment]
@KeyKy  thank you
