### ISSUE TITLE
about channelwise convolution

### ISSUE THREAD

**Issue by wenhe-jia** [KeyKy/mobilenet-mxnet#9]
I noticed that you have used **ChannelwiseConvolution** in `mobilenet-symbol.json` file and `mobilenet-faster.py`. I am using mxnet of version 0.11.1, do i have to use **ChannelwiseConvolution** with **depthwiseConvolution** instead? Because your update say that mxnet 0.11.1 support **depthwiseConvolution**.
Thanks for your reply!

**Comment by KeyKy** [comment]
Now you do not need to use ChannelwiseConvolution just use num_group in mxnet 0.11.1. I will delete the mobilenet-faster.py symbol.

**Comment by BiranLi** [comment]
@KeyKy @LeonJWH  And Cudnn V7 support grouped conv now!

**Comment by KeyKy** [comment]
1. Up to 2.5x faster training of ResNet50 and 3x faster training of NMT language translation LSTM RNNs on Tesla V100 vs. Tesla P100
2. Accelerated convolutions using mixed-precision Tensor Cores operations on Volta GPUs
3. Grouped Convolutions for models such as ResNeXt and Xception and CTC (Connectionist Temporal Classification) loss layer for temporal classification

Good to hear that!

**Comment by BiranLi** [comment]
It approch 10% up in speed of normal conv.

**Comment by wenhe-jia** [comment]
In repo **https://github.com/shicai/MobileNet-Caffe** only regular conv layers are used with **group=32** as depthwise conv layers, what about depthwise convolution? Is there any difference between standard convolution and depthwise convolution?

**Comment by wenhe-jia** [comment]
ok, thanks a lot!
